name: master_deploy_work

on:
  push:
    branches:
      - master

permissions:
  id-token: write     # Essential for OIDC AssumeRole 
  contents: read      # for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # GitHub OIDC for AWS IAM Role Assume
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ap-northeast-2  # Seoul 

      # bucket including dot(.) : path-style 강제 (ex : web.example.com)
      - name: Force S3 path-style for dotted bucket names
        run: |
          aws configure set default.s3.addressing_style path

      # S3 Source remove  
      - name: Remove S3 Source 
        run: |
          aws s3 rm s3://${{ vars.S3_BUCKETNAME }}/pilot/  --recursive  
 

      # S3 Upload and Sync 
      - name: Deploy (S3 sync)
        run: |
          aws s3 sync ./src s3://${{ vars.S3_BUCKETNAME }}/pilot/ \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore"

      # CloudFront Invalidation (Global Service : region no need)
      - name: CDN invalidate
        run: |
          echo "CLOUDFRONT_DISTRIBUTION_ID=${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}"
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/pilot/*"
